apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dev-ingress
  labels:
    app: dev
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dev
            port:
              number: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: dev
  labels:
    app: dev
spec:
  ports:
  - port: 8888
  selector:
    app: dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev
  template:
    metadata:
      labels:
        app: dev
    spec:
      containers:
      - name: dev
        image: wil42/playground:v1
        env:
        - name: APP_NAME
          value: dev
        ports:
        - containerPort: 8888
